# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2025-01-02T15:53:48+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, List, Literal, Optional, Union

from pydantic import BaseModel, EmailStr, Field, RootModel, conint, constr


class AccountLeaderboardType(RootModel[Literal['achievements_points']]):
    root: Literal['achievements_points'] = Field(..., title='AccountLeaderboardType')


class AccountLeaderboardTypeAZAZ09(RootModel[AccountLeaderboardType]):
    root: AccountLeaderboardType


class AccountStatus(Enum):
    standard = 'standard'
    founder = 'founder'
    gold_founder = 'gold_founder'
    vip_founder = 'vip_founder'


class AchievementRewardsSchema(BaseModel):
    gold: int = Field(..., description='Gold rewards.', title='Gold')


class AchievementType(Enum):
    combat_kill = 'combat_kill'
    combat_drop = 'combat_drop'
    combat_level = 'combat_level'
    gathering = 'gathering'
    crafting = 'crafting'
    recycling = 'recycling'
    task = 'task'
    other = 'other'


class AchievementTypeAZAZ09(RootModel[AchievementType]):
    root: AchievementType


class ActionType(Enum):
    movement = 'movement'
    fight = 'fight'
    crafting = 'crafting'
    gathering = 'gathering'
    buy_ge = 'buy_ge'
    sell_ge = 'sell_ge'
    cancel_ge = 'cancel_ge'
    delete_item = 'delete_item'
    deposit = 'deposit'
    withdraw = 'withdraw'
    deposit_gold = 'deposit_gold'
    withdraw_gold = 'withdraw_gold'
    equip = 'equip'
    unequip = 'unequip'
    task = 'task'
    christmas_exchange = 'christmas_exchange'
    recycling = 'recycling'
    rest = 'rest'
    use = 'use'
    buy_bank_expansion = 'buy_bank_expansion'


class AddAccountSchema(BaseModel):
    username: constr(pattern=r'^[a-zA-Z0-9_-]+$', min_length=6, max_length=32) = Field(
        ..., description='Your desired username.', title='Username'
    )
    password: constr(pattern=r'^[^\s]+$', min_length=5, max_length=50) = Field(
        ..., description='Your password.', title='Password'
    )
    email: Optional[EmailStr] = Field(None, title='Email')


class AnnouncementSchema(BaseModel):
    message: str = Field(..., description='Announcement text.', title='Message')
    created_at: Optional[datetime] = Field(
        None, description='Datetime of the announcement.', title='Created At'
    )


class BadgeConditionSchema(BaseModel):
    code: str = Field(..., description='Code of the condition.', title='Code')
    quantity: Optional[int] = Field(
        ..., description='Quantity of the condition (if any).', title='Quantity'
    )


class BadgeSchema(BaseModel):
    code: str = Field(
        ...,
        description="Code of the badge. This is the badge's unique identifier (ID).",
        title='Code',
    )
    season: Optional[int] = Field(
        None, description='Season of the badge.', title='Season'
    )
    description: str = Field(
        ..., description='Description of the badge.', title='Description'
    )
    conditions: List[BadgeConditionSchema] = Field(
        ..., description='Conditions to get the badge.', title='Conditions'
    )


class BankExtensionSchema(BaseModel):
    price: conint(ge=0) = Field(
        ..., description='Price of the bank extension.', title='Price'
    )


class BankSchema(BaseModel):
    slots: conint(ge=0) = Field(
        ..., description='Maximum slots in your bank.', title='Slots'
    )
    expansions: conint(ge=0) = Field(
        ..., description='Bank expansions.', title='Expansions'
    )
    next_expansion_cost: conint(ge=0) = Field(
        ..., description='Next expansion cost.', title='Next Expansion Cost'
    )
    gold: conint(ge=0) = Field(
        ..., description='Quantity of gold in your bank.', title='Gold'
    )


class BlockedHitsSchema(BaseModel):
    fire: int = Field(..., description='The amount of fire hits blocked.', title='Fire')
    earth: int = Field(
        ..., description='The amount of earth hits blocked.', title='Earth'
    )
    water: int = Field(
        ..., description='The amount of water hits blocked.', title='Water'
    )
    air: int = Field(..., description='The amount of air hits blocked.', title='Air')
    total: int = Field(
        ..., description='The amount of total hits blocked.', title='Total'
    )


class ChangePassword(BaseModel):
    current_password: constr(pattern=r'^[^\s]+$', min_length=5, max_length=50) = Field(
        ..., description='Your password.', title='Current Password'
    )
    new_password: constr(pattern=r'^[^\s]+$', min_length=5, max_length=50) = Field(
        ..., description='New password.', title='New Password'
    )


class CharacterLeaderboardSchema(BaseModel):
    position: int = Field(
        ..., description='Position in the leaderboard.', title='Position'
    )
    name: str = Field(..., description='Character name.', title='Name')
    account: str = Field(..., description='Account name.', title='Account')
    skin: str = Field(..., description='Character skin code.', title='Skin')
    level: int = Field(..., description='Combat level.', title='Level')
    total_xp: int = Field(
        ..., description='Total XP of your character.', title='Total Xp'
    )
    mining_level: int = Field(..., description='Mining level.', title='Mining Level')
    mining_total_xp: int = Field(
        ..., description='Mining total xp.', title='Mining Total Xp'
    )
    woodcutting_level: int = Field(
        ..., description='Woodcutting level.', title='Woodcutting Level'
    )
    woodcutting_total_xp: int = Field(
        ..., description='Woodcutting total xp.', title='Woodcutting Total Xp'
    )
    fishing_level: int = Field(..., description='Fishing level.', title='Fishing Level')
    fishing_total_xp: int = Field(
        ..., description='Fishing total xp.', title='Fishing Total Xp'
    )
    weaponcrafting_level: int = Field(
        ..., description='Weaponcrafting level.', title='Weaponcrafting Level'
    )
    weaponcrafting_total_xp: int = Field(
        ..., description='Weaponcrafting total xp.', title='Weaponcrafting Total Xp'
    )
    gearcrafting_level: int = Field(
        ..., description='Gearcrafting level.', title='Gearcrafting Level'
    )
    gearcrafting_total_xp: int = Field(
        ..., description='Gearcrafting total xp.', title='Gearcrafting Total Xp'
    )
    jewelrycrafting_level: int = Field(
        ..., description='Jewelrycrafting level.', title='Jewelrycrafting Level'
    )
    jewelrycrafting_total_xp: int = Field(
        ..., description='Jewelrycrafting total xp.', title='Jewelrycrafting Total Xp'
    )
    cooking_level: int = Field(..., description='Cooking level.', title='Cooking Level')
    cooking_total_xp: int = Field(
        ..., description='Cooking total xp.', title='Cooking Total Xp'
    )
    alchemy_level: int = Field(..., description='Alchemy level.', title='Alchemy Level')
    alchemy_total_xp: int = Field(
        ..., description='Alchemy total xp.', title='Alchemy Total Xp'
    )
    gold: int = Field(
        ..., description='The numbers of gold on this character.', title='Gold'
    )


class CharacterLeaderboardType(Enum):
    combat = 'combat'
    woodcutting = 'woodcutting'
    mining = 'mining'
    fishing = 'fishing'
    weaponcrafting = 'weaponcrafting'
    gearcrafting = 'gearcrafting'
    jewelrycrafting = 'jewelrycrafting'
    cooking = 'cooking'
    alchemy = 'alchemy'
    gold = 'gold'


class CharacterLeaderboardTypeAZAZ09(RootModel[CharacterLeaderboardType]):
    root: CharacterLeaderboardType


class CharacterSkin(Enum):
    men1 = 'men1'
    men2 = 'men2'
    men3 = 'men3'
    women1 = 'women1'
    women2 = 'women2'
    women3 = 'women3'


class CooldownSchema(BaseModel):
    total_seconds: int = Field(
        ..., description='The total seconds of the cooldown.', title='Total Seconds'
    )
    remaining_seconds: int = Field(
        ...,
        description='The remaining seconds of the cooldown.',
        title='Remaining Seconds',
    )
    started_at: datetime = Field(
        ..., description='The start of the cooldown.', title='Started At'
    )
    expiration: datetime = Field(
        ..., description='The expiration of the cooldown.', title='Expiration'
    )
    reason: ActionType = Field(..., description='The reason of the cooldown.')


class CraftSkill(Enum):
    weaponcrafting = 'weaponcrafting'
    gearcrafting = 'gearcrafting'
    jewelrycrafting = 'jewelrycrafting'
    cooking = 'cooking'
    woodcutting = 'woodcutting'
    mining = 'mining'
    alchemy = 'alchemy'


class CraftSkillAZAZ09(RootModel[CraftSkill]):
    root: CraftSkill


class CraftingSchema(BaseModel):
    code: constr(pattern=r'^[a-zA-Z0-9_-]+$') = Field(
        ..., description='Craft code.', title='Craft code'
    )
    quantity: Optional[conint(ge=1)] = Field(
        1, description='Quantity of items to craft.', title='Quantity'
    )


class DataPageBadgeSchema(BaseModel):
    data: List[BadgeSchema] = Field(..., title='Data')
    total: Optional[conint(ge=0)] = Field(..., title='Total')
    page: Optional[conint(ge=1)] = Field(..., title='Page')
    size: Optional[conint(ge=1)] = Field(..., title='Size')
    pages: Optional[conint(ge=0)] = Field(None, title='Pages')


class DataPageCharacterLeaderboardSchema(BaseModel):
    data: List[CharacterLeaderboardSchema] = Field(..., title='Data')
    total: Optional[conint(ge=0)] = Field(..., title='Total')
    page: Optional[conint(ge=1)] = Field(..., title='Page')
    size: Optional[conint(ge=1)] = Field(..., title='Size')
    pages: Optional[conint(ge=0)] = Field(None, title='Pages')


class DeleteCharacterSchema(BaseModel):
    name: constr(pattern=r'^[a-zA-Z0-9_-]+$', min_length=3, max_length=12) = Field(
        ..., description='Character name.', title='Name'
    )


class DepositWithdrawGoldSchema(BaseModel):
    quantity: conint(ge=1) = Field(
        ..., description='Quantity of gold.', title='Quantity'
    )


class DestinationSchema(BaseModel):
    x: int = Field(..., description='The x coordinate of the destination.', title='X')
    y: int = Field(..., description='The y coordinate of the destination.', title='Y')


class DropRateSchema(BaseModel):
    code: constr(pattern=r'^[a-zA-Z0-9_-]+$') = Field(
        ..., description='Item code.', title='Item code'
    )
    rate: conint(ge=1) = Field(..., description='Chance rate. (1/rate)', title='Rate')
    min_quantity: conint(ge=1) = Field(
        ..., description='Minimum quantity.', title='Min Quantity'
    )
    max_quantity: conint(ge=1) = Field(
        ..., description='Maximum quantity.', title='Max Quantity'
    )


class DropSchema(BaseModel):
    code: str = Field(..., description='The code of the item.', title='Code')
    quantity: int = Field(
        ..., description='The quantity of the item.', title='Quantity'
    )


class EventContentSchema(BaseModel):
    type: str = Field(..., description='Type of the event.', title='Type')
    code: str = Field(..., description='Code content.', title='Code')


class EventMapSchema(BaseModel):
    x: int = Field(..., description='Position X of the map.', title='X')
    y: int = Field(..., description='Position Y of the map.', title='Y')


class EventSchema(BaseModel):
    name: str = Field(..., description='Name of the event.', title='Name')
    code: str = Field(
        ...,
        description="Code of the event. This is the event's unique identifier (ID).",
        title='Code',
    )
    maps: List[EventMapSchema] = Field(
        ..., description='Map list of the event.', title='Maps'
    )
    skin: str = Field(..., description='Map skin of the event.', title='Skin')
    duration: int = Field(..., description='Duration in minutes.', title='Duration')
    rate: int = Field(
        ..., description='Rate spawn of the event. (1/rate every minute)', title='Rate'
    )
    content: EventContentSchema = Field(..., description='Content of the event.')


class FightResult(Enum):
    win = 'win'
    loss = 'loss'


class FightSchema(BaseModel):
    xp: int = Field(
        ..., description='The amount of xp gained by the fight.', title='Xp'
    )
    gold: int = Field(
        ..., description='The amount of gold gained by the fight.', title='Gold'
    )
    drops: List[DropSchema] = Field(
        ..., description='The items dropped by the fight.', title='Drops'
    )
    turns: int = Field(
        ..., description='Numbers of the turns of the combat.', title='Turns'
    )
    monster_blocked_hits: BlockedHitsSchema = Field(
        ..., description='The amount of blocked hits by the monster.'
    )
    player_blocked_hits: BlockedHitsSchema = Field(
        ..., description='The amount of blocked hits by the player.'
    )
    logs: List[str] = Field(..., description='The fight logs.', title='Logs')
    result: FightResult = Field(..., description='The result of the fight.')


class GEBuyOrderSchema(BaseModel):
    id: str = Field(..., description='Order id.', title='Id')
    quantity: conint(ge=1, le=100) = Field(
        ..., description='Item quantity.', title='Quantity'
    )


class GECancelOrderSchema(BaseModel):
    id: str = Field(..., description='Order id.', title='Id')


class GEOrderCreatedSchema(BaseModel):
    id: str = Field(..., description='Order id.', title='Id')
    created_at: datetime = Field(
        ..., description='Order created at.', title='Created At'
    )
    code: constr(pattern=r'^[a-zA-Z0-9_-]+$') = Field(
        ..., description='Item code.', title='Code'
    )
    quantity: conint(ge=1, le=100) = Field(
        ..., description='Item quantity.', title='Quantity'
    )
    price: conint(ge=1) = Field(..., description='Item price per unit.', title='Price')
    total_price: conint(ge=1) = Field(
        ..., description='Total price.', title='Total Price'
    )
    tax: conint(ge=1) = Field(
        ..., description='Order creation tax (5%, minimum 1)', title='Tax'
    )


class GEOrderCreationrSchema(BaseModel):
    code: constr(pattern=r'^[a-zA-Z0-9_-]+$') = Field(
        ..., description='Item code.', title='Code'
    )
    quantity: conint(ge=1, le=100) = Field(
        ..., description='Item quantity.', title='Quantity'
    )
    price: conint(ge=1, le=1000000000) = Field(
        ..., description='Item price per unit.', title='Price'
    )


class GEOrderSchema(BaseModel):
    id: str = Field(..., description='Order id.', title='Id')
    seller: str = Field(..., description='Seller account name.', title='Seller')
    code: str = Field(..., description='Item code.', title='Code')
    quantity: conint(ge=1, le=100) = Field(
        ..., description='Item quantity.', title='Quantity'
    )
    price: conint(ge=1) = Field(..., description='Item price per unit.', title='Price')
    created_at: datetime = Field(
        ..., description='Order created at.', title='Created At'
    )


class GETransactionSchema(BaseModel):
    id: str = Field(..., description='Order id.', title='Id')
    code: str = Field(..., description='Item code.', title='Code')
    quantity: int = Field(..., description='Item quantity.', title='Quantity')
    price: int = Field(..., description='Item price.', title='Price')
    total_price: int = Field(
        ..., description='Total price of the transaction.', title='Total Price'
    )


class GatheringSkill(Enum):
    mining = 'mining'
    woodcutting = 'woodcutting'
    fishing = 'fishing'
    alchemy = 'alchemy'


class GatheringSkillAZAZ09(RootModel[GatheringSkill]):
    root: GatheringSkill


class GeOrderHistorySchema(BaseModel):
    order_id: str = Field(..., description='Order id.', title='Order Id')
    seller: str = Field(..., description='Seller account name.', title='Seller')
    buyer: str = Field(..., description='Buyer account name.', title='Buyer')
    code: str = Field(..., description='Item code.', title='Code')
    quantity: conint(ge=1, le=100) = Field(
        ..., description='Item quantity.', title='Quantity'
    )
    price: conint(ge=1) = Field(..., description='Item price per unit.', title='Price')
    sold_at: datetime = Field(..., description='Sale datetime.', title='Sold At')


class GoldSchema(BaseModel):
    quantity: conint(ge=0) = Field(
        ..., description='Quantity of gold.', title='Quantity'
    )


class InventorySlot(BaseModel):
    slot: int = Field(..., description='Inventory slot identifier.', title='Slot')
    code: str = Field(..., description='Item code.', title='Code')
    quantity: int = Field(..., description='Quantity in the slot.', title='Quantity')


class ItemEffectSchema(BaseModel):
    name: str = Field(..., description='Effect name.', title='Name')
    value: int = Field(..., description='Effect value.', title='Value')


class ItemSlot(Enum):
    weapon = 'weapon'
    shield = 'shield'
    helmet = 'helmet'
    body_armor = 'body_armor'
    leg_armor = 'leg_armor'
    boots = 'boots'
    ring1 = 'ring1'
    ring2 = 'ring2'
    amulet = 'amulet'
    artifact1 = 'artifact1'
    artifact2 = 'artifact2'
    artifact3 = 'artifact3'
    utility1 = 'utility1'
    utility2 = 'utility2'


class ItemType(Enum):
    utility = 'utility'
    body_armor = 'body_armor'
    weapon = 'weapon'
    resource = 'resource'
    leg_armor = 'leg_armor'
    helmet = 'helmet'
    boots = 'boots'
    shield = 'shield'
    amulet = 'amulet'
    ring = 'ring'
    artifact = 'artifact'
    currency = 'currency'
    consumable = 'consumable'


class ItemTypeAZAZ09(RootModel[ItemType]):
    root: ItemType


class LogType(Enum):
    spawn = 'spawn'
    movement = 'movement'
    fight = 'fight'
    crafting = 'crafting'
    gathering = 'gathering'
    buy_ge = 'buy_ge'
    sell_ge = 'sell_ge'
    cancel_ge = 'cancel_ge'
    delete_item = 'delete_item'
    deposit = 'deposit'
    withdraw = 'withdraw'
    deposit_gold = 'deposit_gold'
    withdraw_gold = 'withdraw_gold'
    equip = 'equip'
    unequip = 'unequip'
    new_task = 'new_task'
    task_exchange = 'task_exchange'
    task_cancelled = 'task_cancelled'
    task_completed = 'task_completed'
    task_trade = 'task_trade'
    christmas_exchange = 'christmas_exchange'
    recycling = 'recycling'
    rest = 'rest'
    use = 'use'
    buy_bank_expansion = 'buy_bank_expansion'
    achievement = 'achievement'


class MapContentSchema(BaseModel):
    type: str = Field(..., description='Type of the content.', title='Type')
    code: str = Field(..., description='Code of the content.', title='Code')


class MapContentType(Enum):
    monster = 'monster'
    resource = 'resource'
    workshop = 'workshop'
    bank = 'bank'
    grand_exchange = 'grand_exchange'
    tasks_master = 'tasks_master'


class MapContentTypeAZAZ09(RootModel[MapContentType]):
    root: MapContentType


class MapSchema(BaseModel):
    name: str = Field(..., description='Name of the map.', title='Name')
    skin: str = Field(..., description='Skin of the map.', title='Skin')
    x: int = Field(..., description='Position X of the map.', title='X')
    y: int = Field(..., description='Position Y of the map.', title='Y')
    content: Optional[MapContentSchema] = Field(..., description='Content of the map.')


class MonsterSchema(BaseModel):
    name: str = Field(..., description='Name of the monster.', title='Name')
    code: str = Field(
        ...,
        description="The code of the monster. This is the monster's unique identifier (ID).",
        title='Code',
    )
    level: int = Field(..., description='Monster level.', title='Level')
    hp: int = Field(..., description='Monster hit points.', title='Hp')
    attack_fire: int = Field(
        ..., description='Monster fire attack.', title='Attack Fire'
    )
    attack_earth: int = Field(
        ..., description='Monster earth attack.', title='Attack Earth'
    )
    attack_water: int = Field(
        ..., description='Monster water attack.', title='Attack Water'
    )
    attack_air: int = Field(..., description='Monster air attack.', title='Attack Air')
    res_fire: int = Field(
        ..., description='Monster % fire resistance.', title='Res Fire'
    )
    res_earth: int = Field(
        ..., description='Monster % earth resistance.', title='Res Earth'
    )
    res_water: int = Field(
        ..., description='Monster % water resistance.', title='Res Water'
    )
    res_air: int = Field(..., description='Monster % air resistance.', title='Res Air')
    min_gold: int = Field(
        ..., description='Monster minimum gold drop. ', title='Min Gold'
    )
    max_gold: int = Field(
        ..., description='Monster maximum gold drop. ', title='Max Gold'
    )
    drops: List[DropRateSchema] = Field(
        ...,
        description='Monster drops. This is a list of items that the monster drops after killing the monster. ',
        title='Drops',
    )


class MyAccountDetails(BaseModel):
    username: str = Field(..., description='Username.', title='Username')
    email: EmailStr = Field(..., description='Email.', title='Email')
    subscribed: bool = Field(
        ..., description='Subscribed for the current season.', title='Subscribed'
    )
    status: AccountStatus = Field(..., description='Member status.')
    badges: Optional[List] = Field(None, description='Account badges.', title='Badges')
    gems: int = Field(..., description='Gems.', title='Gems')
    achievements_points: int = Field(
        ..., description='Achievement points.', title='Achievements Points'
    )
    banned: bool = Field(..., description='Banned.', title='Banned')
    ban_reason: Optional[str] = Field(
        None, description='Ban reason.', title='Ban Reason'
    )


class MyAccountDetailsSchema(BaseModel):
    data: MyAccountDetails


class RecyclingItemsSchema(BaseModel):
    items: List[DropSchema] = Field(..., description='Objects received.', title='Items')


class RecyclingSchema(BaseModel):
    code: constr(pattern=r'^[a-zA-Z0-9_-]+$') = Field(
        ..., description='Item code.', title='Item code'
    )
    quantity: Optional[conint(ge=1)] = Field(
        1, description='Quantity of items to recycle.', title='Quantity'
    )


class ResourceSchema(BaseModel):
    name: str = Field(..., description='The name of the resource', title='Name')
    code: str = Field(
        ...,
        description="The code of the resource. This is the resource's unique identifier (ID).",
        title='Code',
    )
    skill: GatheringSkill = Field(
        ...,
        description='The skill required to gather this resource.',
        title='Skill code',
    )
    level: int = Field(
        ...,
        description='The skill level required to gather this resource.',
        title='Level',
    )
    drops: List[DropRateSchema] = Field(
        ..., description='The drops of this resource.', title='Drops'
    )


class ResponseSchema(BaseModel):
    message: str = Field(..., title='Message')


class RewardResponseSchema(BaseModel):
    data: DropRateSchema


class SimpleItemSchema(BaseModel):
    code: constr(pattern=r'^[a-zA-Z0-9_-]+$') = Field(
        ..., description='Item code.', title='Code'
    )
    quantity: conint(ge=1) = Field(..., description='Item quantity.', title='Quantity')


class Skill(Enum):
    weaponcrafting = 'weaponcrafting'
    gearcrafting = 'gearcrafting'
    jewelrycrafting = 'jewelrycrafting'
    cooking = 'cooking'
    woodcutting = 'woodcutting'
    mining = 'mining'
    alchemy = 'alchemy'
    fishing = 'fishing'


class SkillInfoSchema(BaseModel):
    xp: int = Field(..., description='The amount of xp gained.', title='Xp')
    items: List[DropSchema] = Field(..., description='Objects received.', title='Items')


class SkillAZAZ09(RootModel[Skill]):
    root: Skill


class StatusSchema(BaseModel):
    status: str = Field(..., description='Server status', title='Status')
    version: str = Field(..., description='Game version.', title='Version')
    max_level: int = Field(..., description='Maximum level.', title='Max Level')
    characters_online: int = Field(
        ..., description='Characters online.', title='Characters Online'
    )
    server_time: datetime = Field(..., description='Server time.', title='Server Time')
    announcements: List[AnnouncementSchema] = Field(
        ..., description='Server announcements.', title='Announcements'
    )
    last_wipe: str = Field(..., description='Last server wipe.', title='Last Wipe')
    next_wipe: str = Field(..., description='Next server wipe.', title='Next Wipe')


class TaskTradeSchema(BaseModel):
    code: str = Field(..., description='Item code.', title='Code')
    quantity: int = Field(..., description='Item quantity.', title='Quantity')


class TaskType(Enum):
    monsters = 'monsters'
    items = 'items'


class TaskTypeAZAZ09(RootModel[TaskType]):
    root: TaskType


class TokenResponseSchema(BaseModel):
    token: str = Field(..., title='Token')


class UnequipSchema(BaseModel):
    slot: ItemSlot = Field(..., description='Item slot.')
    quantity: Optional[conint(ge=1, le=100)] = Field(
        1, description='Item quantity. Applicable to utilitys only.', title='Quantity'
    )


class ValidationError(BaseModel):
    loc: List[Union[str, int]] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class AccountAchievementSchema(BaseModel):
    name: str = Field(..., description='Name of the achievement.', title='Name')
    code: str = Field(..., description='Code of the achievement. ', title='Code')
    description: str = Field(
        ..., description='Description of the achievement.', title='Description'
    )
    points: int = Field(
        ...,
        description='Points of the achievement. Used for the leaderboard.',
        title='Points',
    )
    type: AchievementType = Field(..., description='Type of achievement.')
    target: Optional[str] = Field(
        ..., description='Target of the achievement.', title='Target'
    )
    total: int = Field(..., description='Total to do.', title='Total')
    rewards: AchievementRewardsSchema = Field(..., description='Rewards.')
    current: int = Field(..., description='Current progress.', title='Current')
    completed_at: Optional[datetime] = Field(
        ..., description='Completed at.', title='Completed At'
    )


class AccountDetails(BaseModel):
    username: str = Field(..., description='Username.', title='Username')
    subscribed: bool = Field(
        ..., description='Subscribed for the current season.', title='Subscribed'
    )
    status: AccountStatus = Field(..., description='Member status.')
    badges: Optional[List] = Field(None, description='Account badges.', title='Badges')
    achievements_points: int = Field(
        ..., description='Achievement points.', title='Achievements Points'
    )
    banned: bool = Field(..., description='Banned.', title='Banned')
    ban_reason: Optional[str] = Field(
        None, description='Ban reason.', title='Ban Reason'
    )


class AccountDetailsSchema(BaseModel):
    data: AccountDetails


class AccountLeaderboardSchema(BaseModel):
    position: int = Field(
        ..., description='Position in the leaderboard.', title='Position'
    )
    account: str = Field(..., description='Account name.', title='Account')
    status: AccountStatus = Field(..., description='Member status.')
    achievements_points: int = Field(
        ..., description='Achievements points.', title='Achievements Points'
    )


class AchievementSchema(BaseModel):
    name: str = Field(..., description='Name of the achievement.', title='Name')
    code: str = Field(..., description='Code of the achievement. ', title='Code')
    description: str = Field(
        ..., description='Description of the achievement.', title='Description'
    )
    points: int = Field(
        ...,
        description='Points of the achievement. Used for the leaderboard.',
        title='Points',
    )
    type: AchievementType = Field(..., description='Type of achievement.')
    target: Optional[str] = Field(
        ..., description='Target of the achievement.', title='Target'
    )
    total: int = Field(..., description='Total to do.', title='Total')
    rewards: AchievementRewardsSchema = Field(..., description='Rewards.')


class ActiveEventSchema(BaseModel):
    name: str = Field(..., description='Name of the event.', title='Name')
    code: str = Field(
        ...,
        description="Code of the event. This is the event's unique identifier (ID).",
        title='Code',
    )
    map: MapSchema = Field(..., description='Map of the event.')
    previous_skin: str = Field(
        ..., description='Previous map skin.', title='Previous Skin'
    )
    duration: int = Field(..., description='Duration in minutes.', title='Duration')
    expiration: datetime = Field(
        ..., description='Expiration datetime.', title='Expiration'
    )
    created_at: datetime = Field(..., description='Start datetime.', title='Created At')


class AddCharacterSchema(BaseModel):
    name: constr(pattern=r'^[a-zA-Z0-9_-]+$', min_length=3, max_length=12) = Field(
        ...,
        description="Your desired character name. It's unique and all players can see it.",
        title='Name',
    )
    skin: CharacterSkin = Field(..., description='Your desired skin.')


class BadgeResponseSchema(BaseModel):
    data: BadgeSchema


class BankResponseSchema(BaseModel):
    data: BankSchema


class CharacterSchema(BaseModel):
    name: str = Field(..., description='Name of the character.', title='Name')
    account: str = Field(..., description='Account name.', title='Account')
    skin: CharacterSkin = Field(..., description='Character skin code.')
    level: int = Field(..., description='Combat level.', title='Level')
    xp: int = Field(
        ..., description='The current xp level of the combat level.', title='Xp'
    )
    max_xp: int = Field(
        ..., description='XP required to level up the character.', title='Max Xp'
    )
    gold: int = Field(
        ..., description='The numbers of gold on this character.', title='Gold'
    )
    speed: int = Field(
        ...,
        description='*Not available, on the roadmap. Character movement speed.',
        title='Speed',
    )
    mining_level: int = Field(..., description='Mining level.', title='Mining Level')
    mining_xp: int = Field(
        ..., description='The current xp level of the Mining skill.', title='Mining Xp'
    )
    mining_max_xp: int = Field(
        ...,
        description='Mining XP required to level up the skill.',
        title='Mining Max Xp',
    )
    woodcutting_level: int = Field(
        ..., description='Woodcutting level.', title='Woodcutting Level'
    )
    woodcutting_xp: int = Field(
        ...,
        description='The current xp level of the Woodcutting skill.',
        title='Woodcutting Xp',
    )
    woodcutting_max_xp: int = Field(
        ...,
        description='Woodcutting XP required to level up the skill.',
        title='Woodcutting Max Xp',
    )
    fishing_level: int = Field(..., description='Fishing level.', title='Fishing Level')
    fishing_xp: int = Field(
        ...,
        description='The current xp level of the Fishing skill.',
        title='Fishing Xp',
    )
    fishing_max_xp: int = Field(
        ...,
        description='Fishing XP required to level up the skill.',
        title='Fishing Max Xp',
    )
    weaponcrafting_level: int = Field(
        ..., description='Weaponcrafting level.', title='Weaponcrafting Level'
    )
    weaponcrafting_xp: int = Field(
        ...,
        description='The current xp level of the Weaponcrafting skill.',
        title='Weaponcrafting Xp',
    )
    weaponcrafting_max_xp: int = Field(
        ...,
        description='Weaponcrafting XP required to level up the skill.',
        title='Weaponcrafting Max Xp',
    )
    gearcrafting_level: int = Field(
        ..., description='Gearcrafting level.', title='Gearcrafting Level'
    )
    gearcrafting_xp: int = Field(
        ...,
        description='The current xp level of the Gearcrafting skill.',
        title='Gearcrafting Xp',
    )
    gearcrafting_max_xp: int = Field(
        ...,
        description='Gearcrafting XP required to level up the skill.',
        title='Gearcrafting Max Xp',
    )
    jewelrycrafting_level: int = Field(
        ..., description='Jewelrycrafting level.', title='Jewelrycrafting Level'
    )
    jewelrycrafting_xp: int = Field(
        ...,
        description='The current xp level of the Jewelrycrafting skill.',
        title='Jewelrycrafting Xp',
    )
    jewelrycrafting_max_xp: int = Field(
        ...,
        description='Jewelrycrafting XP required to level up the skill.',
        title='Jewelrycrafting Max Xp',
    )
    cooking_level: int = Field(
        ...,
        description='The current xp level of the Cooking skill.',
        title='Cooking Level',
    )
    cooking_xp: int = Field(..., description='Cooking XP.', title='Cooking Xp')
    cooking_max_xp: int = Field(
        ...,
        description='Cooking XP required to level up the skill.',
        title='Cooking Max Xp',
    )
    alchemy_level: int = Field(..., description='Alchemy level.', title='Alchemy Level')
    alchemy_xp: int = Field(..., description='Alchemy XP.', title='Alchemy Xp')
    alchemy_max_xp: int = Field(
        ...,
        description='Alchemy XP required to level up the skill.',
        title='Alchemy Max Xp',
    )
    hp: int = Field(..., description='Character actual HP.', title='Hp')
    max_hp: int = Field(..., description='Character max HP.', title='Max Hp')
    haste: int = Field(
        ...,
        description='*Character Haste. Increase speed attack (reduce fight cooldown)',
        title='Haste',
    )
    critical_strike: int = Field(
        ...,
        description="*Not available, on the roadmap. Character Critical   Strike. Critical strikes increase the attack's damage.",
        title='Critical Strike',
    )
    stamina: int = Field(
        ...,
        description='*Not available, on the roadmap. Regenerates life at the start of each turn.',
        title='Stamina',
    )
    attack_fire: int = Field(..., description='Fire attack.', title='Attack Fire')
    attack_earth: int = Field(..., description='Earth attack.', title='Attack Earth')
    attack_water: int = Field(..., description='Water attack.', title='Attack Water')
    attack_air: int = Field(..., description='Air attack.', title='Attack Air')
    dmg_fire: int = Field(..., description='% Fire damage.', title='Dmg Fire')
    dmg_earth: int = Field(..., description='% Earth damage.', title='Dmg Earth')
    dmg_water: int = Field(..., description='% Water damage.', title='Dmg Water')
    dmg_air: int = Field(..., description='% Air damage.', title='Dmg Air')
    res_fire: int = Field(..., description='% Fire resistance.', title='Res Fire')
    res_earth: int = Field(..., description='% Earth resistance.', title='Res Earth')
    res_water: int = Field(..., description='% Water resistance.', title='Res Water')
    res_air: int = Field(..., description='% Air resistance.', title='Res Air')
    x: int = Field(..., description='Character x coordinate.', title='X')
    y: int = Field(..., description='Character y coordinate.', title='Y')
    cooldown: int = Field(..., description='Cooldown in seconds.', title='Cooldown')
    cooldown_expiration: Optional[datetime] = Field(
        None, description='Datetime Cooldown expiration.', title='Cooldown Expiration'
    )
    weapon_slot: str = Field(..., description='Weapon slot.', title='Weapon Slot')
    shield_slot: str = Field(..., description='Shield slot.', title='Shield Slot')
    helmet_slot: str = Field(..., description='Helmet slot.', title='Helmet Slot')
    body_armor_slot: str = Field(
        ..., description='Body armor slot.', title='Body Armor Slot'
    )
    leg_armor_slot: str = Field(
        ..., description='Leg armor slot.', title='Leg Armor Slot'
    )
    boots_slot: str = Field(..., description='Boots slot.', title='Boots Slot')
    ring1_slot: str = Field(..., description='Ring 1 slot.', title='Ring1 Slot')
    ring2_slot: str = Field(..., description='Ring 2 slot.', title='Ring2 Slot')
    amulet_slot: str = Field(..., description='Amulet slot.', title='Amulet Slot')
    artifact1_slot: str = Field(
        ..., description='Artifact 1 slot.', title='Artifact1 Slot'
    )
    artifact2_slot: str = Field(
        ..., description='Artifact 2 slot.', title='Artifact2 Slot'
    )
    artifact3_slot: str = Field(
        ..., description='Artifact 3 slot.', title='Artifact3 Slot'
    )
    utility1_slot: str = Field(
        ..., description='Utility 1 slot.', title='Utility1 Slot'
    )
    utility1_slot_quantity: conint(ge=0) = Field(
        ..., description='Utility 1 quantity.', title='Utility1 Slot Quantity'
    )
    utility2_slot: str = Field(
        ..., description='Utility 2 slot.', title='Utility2 Slot'
    )
    utility2_slot_quantity: conint(ge=0) = Field(
        ..., description='Utility 2 quantity.', title='Utility2 Slot Quantity'
    )
    task: str = Field(..., description='Task in progress.', title='Task')
    task_type: str = Field(..., description='Task type.', title='Task Type')
    task_progress: int = Field(
        ..., description='Task progression.', title='Task Progress'
    )
    task_total: int = Field(
        ..., description='Task total objective.', title='Task Total'
    )
    inventory_max_items: int = Field(
        ..., description='Inventory max items.', title='Inventory Max Items'
    )
    inventory: Optional[List[InventorySlot]] = Field(
        None, description='List of inventory slots.', title='Inventory'
    )


class CraftSchema(BaseModel):
    skill: Optional[CraftSkill] = Field(
        None, description='Skill required to craft the item.', title='Skill code'
    )
    level: Optional[int] = Field(
        None, description='The skill level required to craft the item.', title='Level'
    )
    items: Optional[List[SimpleItemSchema]] = Field(
        None, description='List of items required to craft the item.', title='Items'
    )
    quantity: Optional[int] = Field(
        None, description='Quantity of items crafted.', title='Quantity'
    )


class DataPageAccountAchievementSchema(BaseModel):
    data: List[AccountAchievementSchema] = Field(..., title='Data')
    total: Optional[conint(ge=0)] = Field(..., title='Total')
    page: Optional[conint(ge=1)] = Field(..., title='Page')
    size: Optional[conint(ge=1)] = Field(..., title='Size')
    pages: Optional[conint(ge=0)] = Field(None, title='Pages')


class DataPageAccountLeaderboardSchema(BaseModel):
    data: List[AccountLeaderboardSchema] = Field(..., title='Data')
    total: Optional[conint(ge=0)] = Field(..., title='Total')
    page: Optional[conint(ge=1)] = Field(..., title='Page')
    size: Optional[conint(ge=1)] = Field(..., title='Size')
    pages: Optional[conint(ge=0)] = Field(None, title='Pages')


class DataPageAchievementSchema(BaseModel):
    data: List[AchievementSchema] = Field(..., title='Data')
    total: Optional[conint(ge=0)] = Field(..., title='Total')
    page: Optional[conint(ge=1)] = Field(..., title='Page')
    size: Optional[conint(ge=1)] = Field(..., title='Size')
    pages: Optional[conint(ge=0)] = Field(None, title='Pages')


class DataPageActiveEventSchema(BaseModel):
    data: List[ActiveEventSchema] = Field(..., title='Data')
    total: Optional[conint(ge=0)] = Field(..., title='Total')
    page: Optional[conint(ge=1)] = Field(..., title='Page')
    size: Optional[conint(ge=1)] = Field(..., title='Size')
    pages: Optional[conint(ge=0)] = Field(None, title='Pages')


class DataPageDropRateSchema(BaseModel):
    data: List[DropRateSchema] = Field(..., title='Data')
    total: Optional[conint(ge=0)] = Field(..., title='Total')
    page: Optional[conint(ge=1)] = Field(..., title='Page')
    size: Optional[conint(ge=1)] = Field(..., title='Size')
    pages: Optional[conint(ge=0)] = Field(None, title='Pages')


class DataPageEventSchema(BaseModel):
    data: List[EventSchema] = Field(..., title='Data')
    total: Optional[conint(ge=0)] = Field(..., title='Total')
    page: Optional[conint(ge=1)] = Field(..., title='Page')
    size: Optional[conint(ge=1)] = Field(..., title='Size')
    pages: Optional[conint(ge=0)] = Field(None, title='Pages')


class DataPageGEOrderSchema(BaseModel):
    data: List[GEOrderSchema] = Field(..., title='Data')
    total: Optional[conint(ge=0)] = Field(..., title='Total')
    page: Optional[conint(ge=1)] = Field(..., title='Page')
    size: Optional[conint(ge=1)] = Field(..., title='Size')
    pages: Optional[conint(ge=0)] = Field(None, title='Pages')


class DataPageGeOrderHistorySchema(BaseModel):
    data: List[GeOrderHistorySchema] = Field(..., title='Data')
    total: Optional[conint(ge=0)] = Field(..., title='Total')
    page: Optional[conint(ge=1)] = Field(..., title='Page')
    size: Optional[conint(ge=1)] = Field(..., title='Size')
    pages: Optional[conint(ge=0)] = Field(None, title='Pages')


class DataPageMapSchema(BaseModel):
    data: List[MapSchema] = Field(..., title='Data')
    total: Optional[conint(ge=0)] = Field(..., title='Total')
    page: Optional[conint(ge=1)] = Field(..., title='Page')
    size: Optional[conint(ge=1)] = Field(..., title='Size')
    pages: Optional[conint(ge=0)] = Field(None, title='Pages')


class DataPageMonsterSchema(BaseModel):
    data: List[MonsterSchema] = Field(..., title='Data')
    total: Optional[conint(ge=0)] = Field(..., title='Total')
    page: Optional[conint(ge=1)] = Field(..., title='Page')
    size: Optional[conint(ge=1)] = Field(..., title='Size')
    pages: Optional[conint(ge=0)] = Field(None, title='Pages')


class DataPageResourceSchema(BaseModel):
    data: List[ResourceSchema] = Field(..., title='Data')
    total: Optional[conint(ge=0)] = Field(..., title='Total')
    page: Optional[conint(ge=1)] = Field(..., title='Page')
    size: Optional[conint(ge=1)] = Field(..., title='Size')
    pages: Optional[conint(ge=0)] = Field(None, title='Pages')


class DataPageSimpleItemSchema(BaseModel):
    data: List[SimpleItemSchema] = Field(..., title='Data')
    total: Optional[conint(ge=0)] = Field(..., title='Total')
    page: Optional[conint(ge=1)] = Field(..., title='Page')
    size: Optional[conint(ge=1)] = Field(..., title='Size')
    pages: Optional[conint(ge=0)] = Field(None, title='Pages')


class DeleteItemSchema(BaseModel):
    cooldown: CooldownSchema = Field(..., description='Cooldown details.')
    item: SimpleItemSchema = Field(..., description='Item details.')
    character: CharacterSchema = Field(..., description='Player details.')


class EquipSchema(BaseModel):
    code: constr(pattern=r'^[a-zA-Z0-9_-]+$') = Field(
        ..., description='Item code.', title='Code'
    )
    slot: ItemSlot = Field(..., description='Item slot.')
    quantity: Optional[conint(ge=1, le=100)] = Field(
        1, description='Item quantity. Applicable to utilitys only.', title='Quantity'
    )


class GEOrderReponseSchema(BaseModel):
    data: GEOrderSchema


class GEOrderTransactionSchema(BaseModel):
    cooldown: CooldownSchema = Field(..., description='Cooldown details.')
    order: GEOrderCreatedSchema = Field(..., description='Order details.')
    character: CharacterSchema = Field(..., description='Character details.')


class GETransactionListSchema(BaseModel):
    cooldown: CooldownSchema = Field(..., description='Cooldown details.')
    order: GETransactionSchema = Field(..., description='Transaction details.')
    character: CharacterSchema = Field(..., description='Character details.')


class GETransactionResponseSchema(BaseModel):
    data: GETransactionListSchema


class HTTPValidationError(BaseModel):
    detail: Optional[List[ValidationError]] = Field(None, title='Detail')


class ItemSchema(BaseModel):
    name: str = Field(..., description='Item name.', title='Name')
    code: str = Field(
        ...,
        description="Item code. This is the item's unique identifier (ID).",
        title='Code',
    )
    level: conint(ge=1) = Field(..., description='Item level.', title='Level')
    type: str = Field(..., description='Item type.', title='Type')
    subtype: str = Field(..., description='Item subtype.', title='Subtype')
    description: str = Field(..., description='Item description.', title='Description')
    effects: Optional[List[ItemEffectSchema]] = Field(
        None,
        description='List of object effects. For equipment, it will include item stats.',
        title='Effects',
    )
    craft: Optional[CraftSchema] = Field(
        None, description='Craft information. If applicable.'
    )
    tradeable: bool = Field(
        ...,
        description='Item tradeable status. A non-tradeable item cannot be exchanged or sold.',
        title='Tradeable',
    )


class LogSchema(BaseModel):
    character: str = Field(..., description='Character name.', title='Character')
    account: str = Field(..., description='Account character.', title='Account')
    type: LogType = Field(..., description='Type of action.')
    description: str = Field(
        ..., description='Description of action.', title='Description'
    )
    content: Any = Field(..., description='Content of action.', title='Content')
    cooldown: int = Field(..., description='Cooldown in seconds.', title='Cooldown')
    cooldown_expiration: Optional[datetime] = Field(
        ..., description='Datetime of cooldown expiration.', title='Cooldown Expiration'
    )
    created_at: datetime = Field(
        ..., description='Datetime of creation.', title='Created At'
    )


class MapResponseSchema(BaseModel):
    data: MapSchema


class MonsterResponseSchema(BaseModel):
    data: MonsterSchema


class MyCharactersListSchema(BaseModel):
    data: List[CharacterSchema] = Field(
        ..., description='List of your characters.', title='Data'
    )


class RecyclingDataSchema(BaseModel):
    cooldown: CooldownSchema = Field(..., description='Cooldown details.')
    details: RecyclingItemsSchema = Field(..., description='Craft details.')
    character: CharacterSchema = Field(..., description='Player details.')


class RecyclingResponseSchema(BaseModel):
    data: RecyclingDataSchema


class ResourceResponseSchema(BaseModel):
    data: ResourceSchema


class RewardsSchema(BaseModel):
    items: List[SimpleItemSchema] = Field(
        ..., description='Items rewards.', title='Items'
    )
    gold: int = Field(..., description='Gold rewards.', title='Gold')


class SkillDataSchema(BaseModel):
    cooldown: CooldownSchema = Field(..., description='Cooldown details.')
    details: SkillInfoSchema = Field(..., description='Craft details.')
    character: CharacterSchema = Field(..., description='Player details.')


class SkillResponseSchema(BaseModel):
    data: SkillDataSchema


class StatusResponseSchema(BaseModel):
    data: StatusSchema


class TaskCancelledSchema(BaseModel):
    cooldown: CooldownSchema = Field(..., description='Cooldown details.')
    character: CharacterSchema = Field(..., description='Player details.')


class TaskFullSchema(BaseModel):
    code: str = Field(..., description='Task objective.', title='Code')
    level: int = Field(..., description='Task level.', title='Level')
    type: TaskType = Field(..., description='The type of task.', title='Type')
    min_quantity: int = Field(
        ..., description='Minimum amount of task.', title='Min Quantity'
    )
    max_quantity: int = Field(
        ..., description='Maximum amount of task.', title='Max Quantity'
    )
    skill: Optional[str] = Field(
        ..., description='Skill required to complete the task.', title='Skill'
    )
    rewards: RewardsSchema = Field(..., description='Rewards.')


class TaskSchema(BaseModel):
    code: str = Field(..., description='Task objective.', title='Code')
    type: TaskType = Field(..., description='The type of task.', title='Type')
    total: int = Field(
        ..., description='The total required to complete the task.', title='Total'
    )
    rewards: RewardsSchema = Field(..., description='Rewards for completing the task.')


class TaskTradeDataSchema(BaseModel):
    cooldown: CooldownSchema = Field(..., description='Cooldown details.')
    trade: TaskTradeSchema = Field(..., description='Reward details.')
    character: CharacterSchema = Field(..., description='Player details.')


class TaskTradeResponseSchema(BaseModel):
    data: TaskTradeDataSchema


class UseItemSchema(BaseModel):
    cooldown: CooldownSchema = Field(..., description='Cooldown details.')
    item: ItemSchema = Field(..., description='Item details.')
    character: CharacterSchema = Field(..., description='Player details.')


class AchievementResponseSchema(BaseModel):
    data: AchievementSchema


class BankExtensionTransactionSchema(BaseModel):
    cooldown: CooldownSchema = Field(..., description='Cooldown details.')
    transaction: BankExtensionSchema = Field(..., description='Transaction details.')
    character: CharacterSchema = Field(..., description='Player details.')


class BankGoldTransactionSchema(BaseModel):
    cooldown: CooldownSchema = Field(..., description='Cooldown details.')
    bank: GoldSchema = Field(..., description='Bank details.')
    character: CharacterSchema = Field(..., description='Player details.')


class BankItemTransactionSchema(BaseModel):
    cooldown: CooldownSchema = Field(..., description='Cooldown details.')
    item: ItemSchema = Field(..., description='Item details.')
    bank: List[SimpleItemSchema] = Field(
        ..., description='Items in your banks.', title='Bank'
    )
    character: CharacterSchema = Field(..., description='Player details.')


class CharacterFightDataSchema(BaseModel):
    cooldown: CooldownSchema = Field(..., description='Cooldown details.')
    fight: FightSchema = Field(..., description='Fight details.')
    character: CharacterSchema = Field(..., description='Player details.')


class CharacterFightResponseSchema(BaseModel):
    data: CharacterFightDataSchema


class CharacterMovementDataSchema(BaseModel):
    cooldown: CooldownSchema = Field(..., description='Cooldown details')
    destination: MapSchema = Field(..., description='Destination details.')
    character: CharacterSchema = Field(..., description='Character details.')


class CharacterMovementResponseSchema(BaseModel):
    data: CharacterMovementDataSchema


class CharacterResponseSchema(BaseModel):
    data: CharacterSchema


class CharacterRestDataSchema(BaseModel):
    cooldown: CooldownSchema = Field(..., description='Cooldown details')
    hp_restored: int = Field(
        ..., description='The amount of HP restored.', title='Hp Restored'
    )
    character: CharacterSchema = Field(..., description='Character details.')


class CharacterRestResponseSchema(BaseModel):
    data: CharacterRestDataSchema


class DataPageItemSchema(BaseModel):
    data: List[ItemSchema] = Field(..., title='Data')
    total: Optional[conint(ge=0)] = Field(..., title='Total')
    page: Optional[conint(ge=1)] = Field(..., title='Page')
    size: Optional[conint(ge=1)] = Field(..., title='Size')
    pages: Optional[conint(ge=0)] = Field(None, title='Pages')


class DataPageLogSchema(BaseModel):
    data: List[LogSchema] = Field(..., title='Data')
    total: Optional[conint(ge=0)] = Field(..., title='Total')
    page: Optional[conint(ge=1)] = Field(..., title='Page')
    size: Optional[conint(ge=1)] = Field(..., title='Size')
    pages: Optional[conint(ge=0)] = Field(None, title='Pages')


class DataPageTaskFullSchema(BaseModel):
    data: List[TaskFullSchema] = Field(..., title='Data')
    total: Optional[conint(ge=0)] = Field(..., title='Total')
    page: Optional[conint(ge=1)] = Field(..., title='Page')
    size: Optional[conint(ge=1)] = Field(..., title='Size')
    pages: Optional[conint(ge=0)] = Field(None, title='Pages')


class DeleteItemResponseSchema(BaseModel):
    data: DeleteItemSchema


class EquipRequestSchema(BaseModel):
    cooldown: CooldownSchema = Field(..., description='Cooldown details.')
    slot: ItemSlot = Field(..., description='Item slot.')
    item: ItemSchema = Field(..., description='Item details.')
    character: CharacterSchema = Field(..., description='Player details.')


class EquipmentResponseSchema(BaseModel):
    data: EquipRequestSchema


class GECreateOrderTransactionResponseSchema(BaseModel):
    data: GEOrderTransactionSchema


class ItemResponseSchema(BaseModel):
    data: ItemSchema


class RewardDataSchema(BaseModel):
    cooldown: CooldownSchema = Field(..., description='Cooldown details.')
    rewards: RewardsSchema = Field(..., description='Reward details.')
    character: CharacterSchema = Field(..., description='Player details.')


class TaskCancelledResponseSchema(BaseModel):
    data: TaskCancelledSchema


class TaskDataSchema(BaseModel):
    cooldown: CooldownSchema = Field(..., description='Cooldown details.')
    task: TaskSchema = Field(..., description='Task details.')
    character: CharacterSchema = Field(..., description='Player details.')


class TaskFullResponseSchema(BaseModel):
    data: TaskFullSchema


class TaskResponseSchema(BaseModel):
    data: TaskDataSchema


class UseItemResponseSchema(BaseModel):
    data: UseItemSchema


class BankExtensionTransactionResponseSchema(BaseModel):
    data: BankExtensionTransactionSchema


class BankGoldTransactionResponseSchema(BaseModel):
    data: BankGoldTransactionSchema


class BankItemTransactionResponseSchema(BaseModel):
    data: BankItemTransactionSchema


class RewardDataResponseSchema(BaseModel):
    data: RewardDataSchema
